steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_MODE=prod'
      - '--build-arg'
      - 'VITE_BACK_END_PROD=${_VITE_BACK_END_PROD}'
      - '--build-arg'
      - 'VITE_RECAPTCHA_SITE_KEY=${_VITE_RECAPTCHA_SITE_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/frontend'

# Default values
substitutions:
  _VITE_BACK_END_PROD: 'https://api.rentnride.travel/api/v1'
  _VITE_RECAPTCHA_SITE_KEY: ''