steps:
  # Build the container image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_MODE=prod'
      - '--build-arg'
      - 'VITE_BACK_END_PROD=${_VITE_BACK_END_PROD}'
      - '--build-arg'
      - 'VITE_RECAPTCHA_SITE_KEY=${_VITE_RECAPTCHA_SITE_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']

images:
  - 'gcr.io/$PROJECT_ID/frontend'

# Default values (can be overridden)
substitutions:
  _VITE_BACK_END_PROD: 'https://api-289273895966.asia-southeast1.run.app/api/v1/'
  _VITE_RECAPTCHA_SITE_KEY: ''  # Set this when running build
