# Google Cloud Build configuration
# Sử dụng file này để build và deploy tự động với Cloud Build
# Trigger: gcloud builds submit --config=cloudbuild.yaml

steps:
  # Build API
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    dir: 'api'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api:latest'
      - '.'

  # Push API image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/api'
    waitFor: ['build-api']

  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api:$BUILD_ID'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,JWT_SIGNATURE=JWT_SIGNATURE:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-southeast1:bikehub-db'
    waitFor: ['push-api']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'migrate-db'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'migrate-db'
      - '--region'
      - 'asia-southeast1'
    waitFor: ['deploy-api']

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    dir: 'frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:latest'
      - '.'

  # Push Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/frontend'
    waitFor: ['build-frontend']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
    waitFor: ['push-frontend']

  # Build Admin
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-admin'
    dir: 'admin'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://api-289273895966.asia-southeast1.run.app/api/v1/'
      - '-t'
      - 'gcr.io/$PROJECT_ID/admin:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/admin:latest'
      - '.'

  # Push Admin image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-admin'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/admin'
    waitFor: ['build-admin']

  # Deploy Admin to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-admin'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'admin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/admin:$BUILD_ID'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
    waitFor: ['push-admin']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/api:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/api:latest'
  - 'gcr.io/$PROJECT_ID/frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/frontend:latest'
  - 'gcr.io/$PROJECT_ID/admin:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/admin:latest'

# Build timeout
timeout: '1800s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
